-- =========================================================
-- CREACION DE USUARIO
-- =========================================================


CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(150) UNIQUE,
    password VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roles (
    role_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roles_users (
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,

    PRIMARY KEY (user_id, role_id),

    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

CREATE TABLE IF NOT EXISTS permissions (
    permission_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    code VARCHAR(100) UNIQUE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roles_permissions (
    role_id INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,

    PRIMARY KEY (role_id, permission_id),

    FOREIGN KEY (role_id) REFERENCES roles(role_id),
    FOREIGN KEY (permission_id) REFERENCES permissions(permission_id)
);


-- =========================================================
-- CREACIÓN DE HORARIOS
-- =========================================================

CREATE TABLE IF NOT EXISTS "carrera" (
	"id_carrera" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(255),
	PRIMARY KEY("id_carrera")
);

CREATE TABLE IF NOT EXISTS "regimen" (
	"id_regimen" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(255),
	PRIMARY KEY("id_regimen")
);

CREATE TABLE IF NOT EXISTS "ciclo_lectivo" (
	"id_ciclo_lectivo" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"anio" INTEGER,
	"fecha_inicio" DATE,
	"fecha_fin" DATE,
	"estado" VARCHAR(255),
	PRIMARY KEY("id_ciclo_lectivo")
);

CREATE TABLE IF NOT EXISTS "turno" (
	"id_turno" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(255),
	"hora_inicio" TIME,
	"hora_fin" TIME,
	"estado" VARCHAR(255),
	PRIMARY KEY("id_turno")
);

CREATE TABLE IF NOT EXISTS "tipo_cargo" (
	"id_tipo_cargo" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(255),
	"descripcion" VARCHAR(255),
	"admite_suplente" BOOLEAN,
	"estado" VARCHAR(255),
	PRIMARY KEY("id_tipo_cargo")
);

CREATE TABLE IF NOT EXISTS "docente" (
	"id_docente" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"dni" VARCHAR(255),
	"nombre" VARCHAR(255),
	"apellido" VARCHAR(255),
	"telefono" VARCHAR(255),
	"email" VARCHAR(255),
	"legajo" INTEGER,
	"estado" VARCHAR(255),
	PRIMARY KEY("id_docente")
);

CREATE TABLE IF NOT EXISTS "dia" (
	"id_dia" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(255),
	PRIMARY KEY("id_dia")
);

CREATE TABLE IF NOT EXISTS "hora_catedra" (
	"id_hora_catedra" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"numero_franja" INTEGER,
	"hora_desde" TIME,
	"hora_hasta" TIME,
	PRIMARY KEY("id_hora_catedra")
);

CREATE TABLE IF NOT EXISTS "cuatrimestre" (
	"id_cuatrimestre" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(255),
	"numero" INTEGER,
	"fecha_desde" DATE,
	"fecha_hasta" DATE,
	PRIMARY KEY("id_cuatrimestre")
);

CREATE TABLE IF NOT EXISTS "plan_estudio" (
	"id_plan_estudio" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_carrera" INTEGER,
	"nombre" VARCHAR(255),
	"anio_vigencia" INTEGER,
	"fecha_desde" DATE,
	"fecha_hasta" DATE,
	"estado" VARCHAR(255),
	"cantidad_anios" DECIMAL,
	PRIMARY KEY("id_plan_estudio")
);

CREATE TABLE IF NOT EXISTS "espacio_curricular" (
	"id_espacio_curricular" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_plan_estudio" INTEGER,
	"id_regimen" INTEGER,
	"nombre" VARCHAR(255),
	"anio_cursado" INTEGER,
	"horas_semanales" INTEGER,
	"permite_multiple_docente" BOOLEAN,
	"max_docentes" INTEGER,
	"estado" VARCHAR(255),
	PRIMARY KEY("id_espacio_curricular")
);

CREATE TABLE IF NOT EXISTS "plan_estudio_ciclo_lectivo" (
	"id_plan_estudio_ciclo_lectivo" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_plan_estudio" INTEGER,
	"id_ciclo_lectivo" INTEGER,
	"id_turno" INTEGER,
	PRIMARY KEY("id_plan_estudio_ciclo_lectivo")
);

CREATE TABLE IF NOT EXISTS "curso_division" (
	"id_curso_division" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_plan_estudio_ciclo_lectivo" INTEGER,
	"anio_cursado" INTEGER,
	"division" VARCHAR(255),
	"estado" VARCHAR(255),
	PRIMARY KEY("id_curso_division")
);

CREATE TABLE IF NOT EXISTS "espacio_curricular_curso_division" (
	"id_espacio_curricular_curso_division" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_curso_division" INTEGER,
	"id_espacio_cursado" INTEGER,
	"estado" VARCHAR(255),
	PRIMARY KEY("id_espacio_curricular_curso_division")
);

CREATE TABLE IF NOT EXISTS "asignacion_docente" (
	"id_asignacion_docente" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_espacio_curricular_curso_division" INTEGER,
	"id_tipo_cargo" INTEGER,
	"id_docente" INTEGER,
	"fecha_desde" DATE,
	"fecha_hasta" DATE,
	PRIMARY KEY("id_asignacion_docente")
);

CREATE TABLE IF NOT EXISTS "horario" (
	"id_horario" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_cursado" INTEGER,
	"id_cuatrimestre" INTEGER,
	"id_hora_catedra" INTEGER,
	"id_dia" INTEGER,
	"fecha_desde" DATE,
	"fecha_hasta" DATE,
	PRIMARY KEY("id_horario")
);

-- =========================================================
-- CLAVES FORÁNEAS (RELACIONES CORREGIDAS)
-- =========================================================

-- plan_estudio -> carrera
ALTER TABLE "plan_estudio"
ADD CONSTRAINT "fk_plan_estudio_carrera"
FOREIGN KEY("id_carrera") REFERENCES "carrera"("id_carrera")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- espacio_curricular -> plan_estudio
ALTER TABLE "espacio_curricular"
ADD CONSTRAINT "fk_espacio_curricular_plan_estudio"
FOREIGN KEY("id_plan_estudio") REFERENCES "plan_estudio"("id_plan_estudio")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- espacio_curricular -> regimen
ALTER TABLE "espacio_curricular"
ADD CONSTRAINT "fk_espacio_curricular_regimen"
FOREIGN KEY("id_regimen") REFERENCES "regimen"("id_regimen")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- plan_estudio_ciclo_lectivo -> plan_estudio
ALTER TABLE "plan_estudio_ciclo_lectivo"
ADD CONSTRAINT "fk_pecl_plan_estudio"
FOREIGN KEY("id_plan_estudio") REFERENCES "plan_estudio"("id_plan_estudio")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- plan_estudio_ciclo_lectivo -> ciclo_lectivo
ALTER TABLE "plan_estudio_ciclo_lectivo"
ADD CONSTRAINT "fk_pecl_ciclo_lectivo"
FOREIGN KEY("id_ciclo_lectivo") REFERENCES "ciclo_lectivo"("id_ciclo_lectivo")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- plan_estudio_ciclo_lectivo -> turno
ALTER TABLE "plan_estudio_ciclo_lectivo"
ADD CONSTRAINT "fk_pecl_turno"
FOREIGN KEY("id_turno") REFERENCES "turno"("id_turno")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- curso_division -> plan_estudio_ciclo_lectivo
ALTER TABLE "curso_division"
ADD CONSTRAINT "fk_curso_division_pecl"
FOREIGN KEY("id_plan_estudio_ciclo_lectivo") REFERENCES "plan_estudio_ciclo_lectivo"("id_plan_estudio_ciclo_lectivo")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- espacio_curricular_curso_division -> curso_division
ALTER TABLE "espacio_curricular_curso_division"
ADD CONSTRAINT "fk_eccd_curso_division"
FOREIGN KEY("id_curso_division") REFERENCES "curso_division"("id_curso_division")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- espacio_curricular_curso_division -> espacio_curricular
ALTER TABLE "espacio_curricular_curso_division"
ADD CONSTRAINT "fk_eccd_espacio_curricular"
FOREIGN KEY("id_espacio_cursado") REFERENCES "espacio_curricular"("id_espacio_curricular")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- asignacion_docente -> espacio_curricular_curso_division
ALTER TABLE "asignacion_docente"
ADD CONSTRAINT "fk_asignacion_eccd"
FOREIGN KEY("id_espacio_curricular_curso_division") REFERENCES "espacio_curricular_curso_division"("id_espacio_curricular_curso_division")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- asignacion_docente -> tipo_cargo
ALTER TABLE "asignacion_docente"
ADD CONSTRAINT "fk_asignacion_tipo_cargo"
FOREIGN KEY("id_tipo_cargo") REFERENCES "tipo_cargo"("id_tipo_cargo")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- asignacion_docente -> docente
ALTER TABLE "asignacion_docente"
ADD CONSTRAINT "fk_asignacion_docente"
FOREIGN KEY("id_docente") REFERENCES "docente"("id_docente")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- horario -> espacio_curricular_curso_division
ALTER TABLE "horario"
ADD CONSTRAINT "fk_horario_eccd"
FOREIGN KEY("id_cursado") REFERENCES "espacio_curricular_curso_division"("id_espacio_curricular_curso_division")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- horario -> hora_catedra
ALTER TABLE "horario"
ADD CONSTRAINT "fk_horario_hora_catedra"
FOREIGN KEY("id_hora_catedra") REFERENCES "hora_catedra"("id_hora_catedra")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- horario -> dia
ALTER TABLE "horario"
ADD CONSTRAINT "fk_horario_dia"
FOREIGN KEY("id_dia") REFERENCES "dia"("id_dia")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- horario -> cuatrimestre
ALTER TABLE "horario"
ADD CONSTRAINT "fk_horario_cuatrimestre"
FOREIGN KEY("id_cuatrimestre") REFERENCES "cuatrimestre"("id_cuatrimestre")
ON UPDATE NO ACTION ON DELETE NO ACTION;